defaults: &defaults
  working_directory: ~/vue-forest-admin
  docker:
    # custom docker image to run commands in. Thanks Rhinogram, LLC
    - image: rhinogram/node-awscli:latest


version: 2
jobs:

  deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Get Config File
          command: aws s3 cp s3://bluecactus-devops/forestindex/configs/env.js src/
      - run: yarn
      - run:
          name: Build
          command: yarn build:prod
      - run:
          name: Deploy
          command: |
            aws s3 cp dist s3://admin.forestindex.com/ --recursive --storage-class REDUCED_REDUNDANCY --metadata-directive REPLACE --cache-control max-age=600 --acl public-read
            aws s3 sync dist s3://admin.forestindex.com

workflows:
  version: 2

  deploy_prod:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
